# The HouseBlend example

In [1]:
import os
import sys
import time
import matplotlib.pyplot as plt
import numpy as np

module_path = os.path.abspath(os.path.join('../HouseBlend'))
if module_path not in sys.path:
    sys.path.append(module_path)
import HouseBlend as hb

## Setup an example test case
If using for real, first create the contacts.xlsx workbook following the template and leave the test parameter as False (default value).

### User inputs
**n_periods** <br>
The total number of periods you wish to schedule including historic and future. 
Set this to None to have the minimum number of periods required for everyone to meet everyone else

**current_period** <br>
The period number of the first future period to schedule. 
For first ever usage, this should be set to 1 (i.e. you need to schedule from period 1 forwards).
Values > 1 will import previous periods from schedule.xlsx and treat these as having happened and therefore fixed.

**parent_dir** <br>
The folder path containing the input / output files. If it does not exist, it will be created.

In [2]:
n_to_schedule = 1  # total number of periods to schedule. Set to None for minimum number to satisfy all possible meetings.

current_period = 1  # the period from which to schedule. Set to 1 for first usage.

parliament_name = 'example'  # name of parliament - used to create folder for input/output files

## Import input files or create test participants
A single file (hansard file), is used to manage a coffee roulette instance. This file is used to store all the participants data, as input to the scheduler, and stores the schedule history.

Use `import_hansard` with test set to an integer to create a new test group of n participants. For real usage, remove the test parameter (default is false) to use on a defined `parliament_hansard.xlsx` input file.

In [3]:
contacts, dates, availability, schedule, bool_schedule = hb.import_hansard(parliament_name=parliament_name, test=6)

contacts.head()

Creating new participant directory of 6 length for testing at /Users/Engs1825/Documents/GitHub/HouseBlend/example/example/example_hansard.xlsx

,email,Assistant,Assistant email
Person,,,
Brian Peck,BrianPeck@email.com,Brian Peck,BrianPeck@email.com
Alex Howard,AlexHoward@email.com,Alex Howard,AlexHoward@email.com
Anthony Johnson,AnthonyJohnson@email.com,Anthony Johnson,AnthonyJohnson@email.com
Pamela Webb,PamelaWebb@email.com,Pamela Webb,PamelaWebb@email.com
Carlos Williams,CarlosWilliams@email.com,Carlos Williams,CarlosWilliams@email.com

In [4]:
dates

       Start Date   End Date
Period
1      2026-03-01 2026-03-15
2      2026-03-15 2026-03-29
3      2026-03-29 2026-04-12
4      2026-04-12 2026-04-26
5      2026-04-26 2026-05-10

## Run schedule optimisation
Note. There is the option to save the schedule directly. Otherwise, you need to specifically generate the meeting schedule in order to save it.

In [5]:
bool_schedule = hb.run_schedule_optimisation(contacts, dates, availability, schedule, bool_schedule, n_to_schedule, save=True)

## Create readable meeting schedule
Note. You should use the save parameter if you wish to save the schedule to the hansard as official.

In [7]:
meeting_schedule = hb.generate_meeting_schedule(contacts, dates, availability, bool_schedule, save=True, parliament_name="example")
meeting_schedule

                        Period 1
Person
Brian Peck           Pamela Webb
Alex Howard      Carlos Williams
Anthony Johnson      Daniel Hall
Pamela Webb           Brian Peck
Carlos Williams      Alex Howard
Daniel Hall      Anthony Johnson

## Create a single period's list of meetings - ready for mail merge export

In [7]:
all_meetings_period = hb.period_meeting_list(contacts, bool_schedule, 1, save=False, parliament_name=parliament_name)
all_meetings_period

              Person 1         Person 2
0  Christopher Carroll       James Diaz
1        David Huffman  Janice Harrison
2       Austin Hopkins    Angela Durham

## Export for mailmerge

In [8]:
hb.export_for_mailmerge2(
    contacts,
    bool_schedule,
    1,
    dates,
    save=True,
    parliament_name=parliament_name,
    save_prefix='HouseBlend',
    subject=None)

(      mailto full name mailto first name mailto assistant full name  \
 0  Christopher Carroll       Christopher        Christopher Carroll
 1           James Diaz             James                 James Diaz
 2        David Huffman             David              David Huffman
 3      Janice Harrison            Janice            Janice Harrison
 4       Austin Hopkins            Austin             Austin Hopkins
 5        Angela Durham            Angela              Angela Durham

   paired with full name paired with first name  start date    end date  \
 0            James Diaz                  James  02/11/2025  16/11/2025
 1   Christopher Carroll            Christopher  02/11/2025  16/11/2025
 2       Janice Harrison                 Janice  02/11/2025  16/11/2025
 3         David Huffman                  David  02/11/2025  16/11/2025
 4         Angela Durham                 Angela  02/11/2025  16/11/2025
 5        Austin Hopkins                 Austin  02/11/2025  16/11/2025

             start date long              end date long  \
 0  Sunday 2nd November 2025  Sunday 16th November 2025
 1  Sunday 2nd November 2025  Sunday 16th November 2025
 2  Sunday 2nd November 2025  Sunday 16th November 2025
 3  Sunday 2nd November 2025  Sunday 16th November 2025
 4  Sunday 2nd November 2025  Sunday 16th November 2025
 5  Sunday 2nd November 2025  Sunday 16th November 2025

                    mailto email
 0  ChristopherCarroll@email.com
 1           JamesDiaz@email.com
 2        DavidHuffman@email.com
 3      JaniceHarrison@email.com
 4       AustinHopkins@email.com
 5        AngelaDurham@email.com  ,
   mailto assistant full name mailto assistant first name     person full name  \
 0        Christopher Carroll                 Christopher  Christopher Carroll
 1                 James Diaz                       James           James Diaz
 2              David Huffman                       David        David Huffman
 3            Janice Harrison                      Janice      Janice Harrison
 4             Austin Hopkins                      Austin       Austin Hopkins
 5              Angela Durham                      Angela        Angela Durham

   paired with full name paired with assistant full name  \
 0            James Diaz                      James Diaz
 1   Christopher Carroll             Christopher Carroll
 2       Janice Harrison                 Janice Harrison
 3         David Huffman                   David Huffman
 4         Angela Durham                   Angela Durham
 5        Austin Hopkins                  Austin Hopkins

     paired with assistant email  start date    end date  \
 0           JamesDiaz@email.com  02/11/2025  16/11/2025
 1  ChristopherCarroll@email.com  02/11/2025  16/11/2025
 2      JaniceHarrison@email.com  02/11/2025  16/11/2025
 3        DavidHuffman@email.com  02/11/2025  16/11/2025
 4        AngelaDurham@email.com  02/11/2025  16/11/2025
 5       AustinHopkins@email.com  02/11/2025  16/11/2025

             start date long              end date long  \
 0  Sunday 2nd November 2025  Sunday 16th November 2025
 1  Sunday 2nd November 2025  Sunday 16th November 2025
 2  Sunday 2nd November 2025  Sunday 16th November 2025
 3  Sunday 2nd November 2025  Sunday 16th November 2025
 4  Sunday 2nd November 2025  Sunday 16th November 2025
 5  Sunday 2nd November 2025  Sunday 16th November 2025

                    mailto email
 0  ChristopherCarroll@email.com
 1           JamesDiaz@email.com
 2        DavidHuffman@email.com
 3      JaniceHarrison@email.com
 4       AustinHopkins@email.com
 5        AngelaDurham@email.com  )

To run for the second period

In [13]:
# set current period to 2 for next scheduling
current_period = 3

# load hansard again to see any updates
contacts, dates, availability, schedule, bool_schedule = hb.import_hansard(parliament_name=parliament_name)

In [14]:
# update_particpants
contacts, dates, availability, schedule, bool_schedule = hb.participant_update(
    contacts,
    dates,
    availability,
    schedule,
    bool_schedule,
    parliament_name=parliament_name,
    folderpath=None)

No participant changes

In [15]:
bool_schedule = hb.run_schedule_optimisation(contacts, dates, availability, schedule, bool_schedule, n_to_schedule, current_period=current_period, save=True)