# The HouseBlend example

In [1]:
import os
import sys
import time
import matplotlib.pyplot as plt
import numpy as np

module_path = os.path.abspath(os.path.join('../HouseBlend'))
if module_path not in sys.path:
    sys.path.append(module_path)
import HouseBlend as hb

In [8]:
# reload hb
import importlib
importlib.reload(hb)

## Setup an example test case
If using for real, first create the contacts.xlsx workbook following the template and leave the test parameter as False (default value).

### User inputs
**n_periods** <br>
The total number of periods you wish to schedule including historic and future. 
Set this to None to have the minimum number of periods required for everyone to meet everyone else

**current_period** <br>
The period number of the first future period to schedule. 
For first ever usage, this should be set to 1 (i.e. you need to schedule from period 1 forwards).
Values > 1 will import previous periods from schedule.xlsx and treat these as having happened and therefore fixed.

**parent_dir** <br>
The folder path containing the input / output files. If it does not exist, it will be created.

In [9]:
n_to_schedule = 5  # total number of periods to schedule. Set to None for minimum number to satisfy all possible meetings.

current_period = 1  # the period from which to schedule. Set to 1 for first usage.

parliament_name = 'example'  # name of parliament - used to create folder for input/output files

## Import input files or create test participants
A single file (hansard file), is used to manage a coffee roulette instance. This file is used to store all the participants data, as input to the scheduler, and stores the schedule history.

Use `import_hansard` with test set to an integer to create a new test group of n participants. For real usage, remove the test parameter (default is false) to use on a defined `parliament_hansard.xlsx` input file.

In [10]:
contacts, dates, availability, schedule, bool_schedule = hb.import_hansard(parliament_name=parliament_name, test=6)

contacts.head()

Deleting previous hansard file
Creating new participant directory of 6 length for testing at /Users/Engs1825/Documents/GitHub/HouseBlend/example/example/example_hansard.xlsx

                                email      Assistant         Assistant email
Person
Seth Lang          SethLang@email.com      Seth Lang      SethLang@email.com
Charles Brown  CharlesBrown@email.com  Charles Brown  CharlesBrown@email.com
Mark Wilkins    MarkWilkins@email.com   Mark Wilkins   MarkWilkins@email.com
Susan Solis      SusanSolis@email.com    Susan Solis    SusanSolis@email.com
Sophia Scott    SophiaScott@email.com   Sophia Scott   SophiaScott@email.com

In [11]:
dates

       Start Date   End Date
Period
1      2026-03-01 2026-03-15
2      2026-03-15 2026-03-29
3      2026-03-29 2026-04-12
4      2026-04-12 2026-04-26
5      2026-04-26 2026-05-10

## Run schedule optimisation
Note. There is the option to save the schedule directly. Otherwise, you need to specifically generate the meeting schedule in order to save it.

In [ ]:
bool_schedule = hb.run_schedule_optimisation(contacts, dates, availability, schedule, bool_schedule, n_to_schedule, save=True)

Number of periods to schedule (5) is greater than iterative limit (3). Running optimisation iteratively in chunks of 3 periods.
Running optimisation for periods 1 to 3

/Users/Engs1825/miniforge3/envs/HouseBlend/lib/python3.12/site-packages/cvxpy/reductions/solvers/solving_chain_utils.py:41: UserWarning: The problem has an expression with dimension greater than 2. Defaulting to the SCIPY backend for canonicalization.
  warnings.warn(UserWarning(

Running optimisation for periods 4 to 5

## Create readable meeting schedule
Note. You should use the save parameter if you wish to save the schedule to the hansard as official.

In [13]:
meeting_schedule = hb.generate_meeting_schedule(contacts, dates, availability, bool_schedule, save=True, parliament_name="example")
meeting_schedule

,Period 1,Period 2,Period 3,Period 4,Period 5
Person,,,,,
Seth Lang,Charles Brown,Sophia Scott,Mark Wilkins,Susan Solis,Karen Miller
Charles Brown,Seth Lang,Susan Solis,Karen Miller,Mark Wilkins,Sophia Scott
Mark Wilkins,Sophia Scott,Karen Miller,Seth Lang,Charles Brown,Susan Solis
Susan Solis,Karen Miller,Charles Brown,Sophia Scott,Seth Lang,Mark Wilkins
Sophia Scott,Mark Wilkins,Seth Lang,Susan Solis,Karen Miller,Charles Brown
Karen Miller,Susan Solis,Mark Wilkins,Charles Brown,Sophia Scott,Seth Lang

## Create a single period's list of meetings - ready for mail merge export

In [7]:
all_meetings_period = hb.period_meeting_list(contacts, bool_schedule, 1, save=False, parliament_name=parliament_name)
all_meetings_period

          Person 1           Person 2
0  John Pennington  Melissa Hernandez
1     Joshua Sloan   Crystal Figueroa
2     William Sims        Kevin Munoz

## Export for mailmerge

In [ ]:
hb.export_for_mailmerge(
    contacts,
    bool_schedule,
    1,
    dates,
    save=True,
    parliament_name=parliament_name,
    save_prefix='HouseBlend',
    subject=None)

(    mailto full name mailto first name mailto assistant full name  \
 0    John Pennington              John            John Pennington
 1  Melissa Hernandez           Melissa          Melissa Hernandez
 2       Joshua Sloan            Joshua               Joshua Sloan
 3   Crystal Figueroa           Crystal           Crystal Figueroa
 4       William Sims           William               William Sims
 5        Kevin Munoz             Kevin                Kevin Munoz

   paired with full name paired with first name  start date    end date  \
 0     Melissa Hernandez                Melissa  01/03/2026  15/03/2026
 1       John Pennington                   John  01/03/2026  15/03/2026
 2      Crystal Figueroa                Crystal  01/03/2026  15/03/2026
 3          Joshua Sloan                 Joshua  01/03/2026  15/03/2026
 4           Kevin Munoz                  Kevin  01/03/2026  15/03/2026
 5          William Sims                William  01/03/2026  15/03/2026

          start date long           end date long                mailto email
 0  Sunday 1st March 2026  Sunday 15th March 2026    JohnPennington@email.com
 1  Sunday 1st March 2026  Sunday 15th March 2026  MelissaHernandez@email.com
 2  Sunday 1st March 2026  Sunday 15th March 2026       JoshuaSloan@email.com
 3  Sunday 1st March 2026  Sunday 15th March 2026   CrystalFigueroa@email.com
 4  Sunday 1st March 2026  Sunday 15th March 2026       WilliamSims@email.com
 5  Sunday 1st March 2026  Sunday 15th March 2026        KevinMunoz@email.com  ,
   mailto assistant full name mailto assistant first name   person full name  \
 0            John Pennington                        John    John Pennington
 1          Melissa Hernandez                     Melissa  Melissa Hernandez
 2               Joshua Sloan                      Joshua       Joshua Sloan
 3           Crystal Figueroa                     Crystal   Crystal Figueroa
 4               William Sims                     William       William Sims
 5                Kevin Munoz                       Kevin        Kevin Munoz

   paired with full name paired with assistant full name  \
 0     Melissa Hernandez               Melissa Hernandez
 1       John Pennington                 John Pennington
 2      Crystal Figueroa                Crystal Figueroa
 3          Joshua Sloan                    Joshua Sloan
 4           Kevin Munoz                     Kevin Munoz
 5          William Sims                    William Sims

   paired with assistant email  start date    end date        start date long  \
 0  MelissaHernandez@email.com  01/03/2026  15/03/2026  Sunday 1st March 2026
 1    JohnPennington@email.com  01/03/2026  15/03/2026  Sunday 1st March 2026
 2   CrystalFigueroa@email.com  01/03/2026  15/03/2026  Sunday 1st March 2026
 3       JoshuaSloan@email.com  01/03/2026  15/03/2026  Sunday 1st March 2026
 4        KevinMunoz@email.com  01/03/2026  15/03/2026  Sunday 1st March 2026
 5       WilliamSims@email.com  01/03/2026  15/03/2026  Sunday 1st March 2026

             end date long                mailto email
 0  Sunday 15th March 2026    JohnPennington@email.com
 1  Sunday 15th March 2026  MelissaHernandez@email.com
 2  Sunday 15th March 2026       JoshuaSloan@email.com
 3  Sunday 15th March 2026   CrystalFigueroa@email.com
 4  Sunday 15th March 2026       WilliamSims@email.com
 5  Sunday 15th March 2026        KevinMunoz@email.com  )

To run for the second period

In [14]:
# set current period to 2 for next scheduling
current_period = 6

# load hansard again to see any updates
contacts, dates, availability, schedule, bool_schedule = hb.import_hansard(parliament_name=parliament_name)

In [15]:
# update_particpants
contacts, dates, availability, schedule, bool_schedule = hb.participant_update(
    contacts,
    dates,
    availability,
    schedule,
    bool_schedule,
    parliament_name=parliament_name,
    folderpath=None)

No participant changes

In [16]:
bool_schedule = hb.run_schedule_optimisation2(contacts, dates, availability, schedule, bool_schedule, 1, current_period=current_period, save=True)

Adding dates for period 6 as it is missing from the dates sheet.
Running optimisation for periods 6 to 6
Single period, only including past meeting penalty

/Users/Engs1825/miniforge3/envs/HouseBlend/lib/python3.12/site-packages/cvxpy/reductions/solvers/solving_chain_utils.py:41: UserWarning: The problem has an expression with dimension greater than 2. Defaulting to the SCIPY backend for canonicalization.
  warnings.warn(UserWarning(

In [17]:
meeting_schedule = hb.generate_meeting_schedule(contacts, dates, availability, bool_schedule, save=False, parliament_name="example")
meeting_schedule

,Period 1,Period 2,Period 3,Period 4,Period 5,Period 6
Person,,,,,,
Seth Lang,Charles Brown,Sophia Scott,Mark Wilkins,Susan Solis,Karen Miller,Charles Brown
Charles Brown,Seth Lang,Susan Solis,Karen Miller,Mark Wilkins,Sophia Scott,Seth Lang
Mark Wilkins,Sophia Scott,Karen Miller,Seth Lang,Charles Brown,Susan Solis,Sophia Scott
Susan Solis,Karen Miller,Charles Brown,Sophia Scott,Seth Lang,Mark Wilkins,Karen Miller
Sophia Scott,Mark Wilkins,Seth Lang,Susan Solis,Karen Miller,Charles Brown,Mark Wilkins
Karen Miller,Susan Solis,Mark Wilkins,Charles Brown,Sophia Scott,Seth Lang,Susan Solis